const GamesActionTypes = {
    OPEN_FILTERS_PANEL: 'OPEN_FILTERS_PANEL',
    CLOSE_FILTERS_PANEL: 'CLOSE_FILTERS_PANEL',
    TOGGLE_PUBLIC_VISIBILITY_FILTER: 'TOGGLE_PUBLIC_VISIBILITY_FILTER',
    TOGGLE_PRIVATE_VISIBILITY_FILTER: 'TOGGLE_PRIVATE_VISIBILITY_FILTER',
    SET_CREATOR_FILTER: 'SET_CREATOR_FILTER',
    SELECT_GAME: 'SELECT_GAME'
}

export default GamesActionTypes